// Code generated by mockery v1.0.0. DO NOT EDIT.
package z_mocks

import mock "github.com/stretchr/testify/mock"

// Execer is an autogenerated mock type for the Execer type
type Execer struct {
	mock.Mock
}

// Start provides a mock function with given fields:
func (_m *Execer) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Execer) Stop() {
	_m.Called()
}
